Models/Paper.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IAproject.Models
{
    public class Paper
    {
      
        public Guid id { get; set; }
        [Required(ErrorMessage = "You must enter your paper Title")]
        [Display(Name = "Title")]
        public String Title { get; set; }
        [Required(ErrorMessage = "You must enter your Content")]
        [Display(Name = "Content")]
        public String Content { get; set; }
        public virtual ICollection<Auther> authers { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IAproject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/PaperController.cs
using IAproject.Models;
using IAproject.ViewModel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IAproject.Controllers
{
    public class PaperController : Controller
    {
        // GET: Paper
        DefaultConnection db = new DefaultConnection();
        public ActionResult Home()
        {
            var data = db.paper.First();
            List<Paper> papers = new List<Paper>

            {
            new Paper
            {
                Title =data.Title,
                Content = data.Content,
                id = data.id,
                authers = data.authers
       

            }

            };

            
            return View(papers);
        }
        public Paper AddId(Paper Paper)
        {
            Guid id = Guid.NewGuid();

            Paper.id = id;

            return Paper;
        }
        public ActionResult ShowOnePaper(String id)
        {

            Guid prevID = Guid.NewGuid();
         

            var allpapars = db.paper;
            var allauthers = db.auther;
            var paperAuthersIDs = db.papersAuhters.Where(i => i.paperID.ToString() == id);
            List<PaperAuthors> paperAuther = new List<PaperAuthors>();



            // var number = paperAuthersIDs.Where(i => i.paperID == paper.id).Count();
            PaperAuthors temp = new PaperAuthors
                    {
                        paper = allpapars.FirstOrDefault(u => u.id.ToString() ==id),

                    };
                    List<Auther> a = new List<Auther>();
                    foreach (var i in paperAuthersIDs.Where(y => y.paperID.ToString() ==id ))
                    {
                        var authers = allauthers.Where(u => u.Id == i.AuhterID);

                        if (authers != null)
                        {

                            foreach (var l in authers)
                            {
                                a.Add(l);

                            }
                            temp.auther = a;
                        }

                    }
            paperAuther.Add(temp);

                    


                
           
            var data = paperAuther.ToList();
            return View(data);
        }
        public ActionResult show()
        {
            Guid prevID = Guid.NewGuid();
            // var data = db.Database.ExecuteSqlCommand("SELECT  ID, FirstName, Contant, Title, Paper_id , Auther_Id FROM PaperAuthers JOIN Papers ON papers.id=PaperAuhters.Paper_id Join Authers on Auhters.ID= PaperAuhters.Auther_Id; ");
            //ViewBag.st = data.ToString();

 
            var allpapars = db.paper;
            var allauthers = db.auther;
            var paperAuthersIDs = db.papersAuhters.OrderByDescending(i => i.paperID);
            List<PaperAuthors> paperAuther = new List<PaperAuthors>();
            foreach (var papers in paperAuthersIDs)
            {
                if (papers.paperID != prevID)
                {


                    // var number = paperAuthersIDs.Where(i => i.paperID == paper.id).Count();
                    PaperAuthors temp = new PaperAuthors
                    {
                        paper = allpapars.FirstOrDefault(u => u.id == papers.paperID),

                    };
                        List<Auther> a = new List<Auther>();
                    foreach (var i in paperAuthersIDs.Where(y => y.paperID == papers.paperID))
                    {
                        var authers = allauthers.Where(u => u.Id == i.AuhterID);

                        if (authers != null)
                        {
                          
                            foreach (var l in authers)
                            {
                                a.Add(l);

                            }
                            temp.auther = a;
                        }

                    }

                    paperAuther.Add(temp);

                    prevID = papers.paperID;


                }
            }
           var data = paperAuther.ToList();
            return View(data);
        }
        [HttpGet]
        public ActionResult AddPaper()
        {
            

            return View();

        }
        [HttpPost]
        public ActionResult AddPaper(Paper paper)
        {var Email = Session["Email"].ToString();
                    var writer = db.auther.Where(s => s.Email == Email).FirstOrDefault(); 
            if (Session["ID"] != null)
            {  
                if (ModelState.IsValid)
                {


                  
                    AddId(paper);
                    writer.papers = new List<Paper>
                    {
                        paper
                    };
                    paper.authers = new List<Auther>
                    {
                       writer
                    };
                   
                    paper.authers.Add(writer);
                    papersAuther p = new papersAuther
                    {
                        paperID= paper.id,
                        AuhterID= writer.Id
                    };
                    db.papersAuhters.Add(p);
                    db.paper.Add(paper);

                    db.SaveChanges();
                    ModelState.Clear();
                    return RedirectToAction("show");
                }
                ViewBag.state = "Data not valid";
                return View();

            }
            return RedirectToAction("Auther/Login");


        }
        
        public ActionResult AddLike(Guid id)
        {
            Boolean isLikedByThisUser = false;
            likes newlike = new likes();
            if (Session["ID"] == null)
            {
                return RedirectToAction( "Login","Auther");

            }
            var isPaperLikedBefore = db.likes.FirstOrDefault(l => l.paperID == id);
           if(isPaperLikedBefore==null)
            {

                


                newlike.paperID = id;
                newlike.AutherID = Guid.Parse(Session["ID"].ToString());

                db.likes.Add(newlike);
                db.SaveChanges();
            


            }
           
            else
            {
                var allLikesForeThishPaper = db.likes.Where(i => i.paperID == id);
                foreach(var i in allLikesForeThishPaper)
                {
                    if (i.AutherID == Guid.Parse(Session["ID"].ToString()))
                    {
                       
                        isLikedByThisUser = true;
                       
                      
                        db.likes.Remove(i);
                      
                       
                    }
                }  db.SaveChanges();
            }
            if (!isLikedByThisUser)
            {
                    newlike.paperID = id;
                    newlike.AutherID = Guid.Parse(Session["ID"].ToString());
                    db.likes.Add(newlike);
                    db.SaveChanges();
            }
           
            return View();

        }

        public ActionResult AddDisLike(Guid id)
        {
            Boolean isdisLikedByThisUser = false;
            dislike newDislike = new dislike();
            if (Session["ID"] == null)
            {
                return RedirectToAction("Login", "Auther");

            }
            var isPaperdisLikedBefore = db.dislikes.FirstOrDefault(l => l.paperID == id);
            if (isPaperdisLikedBefore == null)
            {

                RedirectToAction("Auther", "Login");


                newDislike.paperID = id;
                newDislike.AutherID = Guid.Parse(Session["ID"].ToString());

                db.dislikes.Add(newDislike);
                db.SaveChanges();



            }

            else
            {
                var alldisLikesForeThishPaper = db.dislikes.Where(i => i.paperID == id);
                foreach (var i in alldisLikesForeThishPaper)
                {
                    if (i.AutherID == Guid.Parse(Session["ID"].ToString()))
                    {

                        isdisLikedByThisUser = true;


                        db.dislikes.Remove(i);


                    }
                }
                db.SaveChanges();
            }
            if (!isdisLikedByThisUser)
            {
                newDislike.paperID = id;
                newDislike.AutherID = Guid.Parse(Session["ID"].ToString());
                db.dislikes.Add(newDislike);
                db.SaveChanges();
            }

            return View();

        }
   

        [HttpPost]
        public ActionResult addComment(String Id  )

        {

            Guid paperID = Guid.Parse(Id);
            String commentContent = Request.Form["Comment"].ToString();

            if (Session["ID"] == null)
            {
                return RedirectToAction("Login", "Auther");
            }
            Comments comment = new Comments
            {
                paperID = paperID,
                AutherID = Guid.Parse(Session["ID"].ToString()),
                Comment = commentContent
            };
          
            db.comments.Add(comment);
            db.SaveChanges();
            return RedirectToAction("show");
        }
       
    }
}
/*
 *  var paperAuthersIDs=db.paperAuthers;
            var allpapars = db.paper;
            var allauthers = db.auther;
            List<paperAutherModel> paperAuther = new List<paperAutherModel>();
            foreach(var papers in paperAuthersIDs)
            {
                int indextemp = 0;
                paperAutherModel temp = new paperAutherModel
                {
                    Paper = allpapars.FirstOrDefault(u => u.id == papers.PaperID),
                    
                };
                foreach (var i in paperAuthersIDs.Where(y => y.PaperID == papers.PaperID))

Views/Paper/AddLike.cshtml
@{
    ViewBag.Title = "AddLike";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>AddLike</h2>
<body>

    <p>Click on the icon to toggle between thumbs-up and thumbs-down (like/dislike):</p>

    <i  class="fa fa-thumbs-up"></i>

    <script>
        function myFunction(x) {
            x.classList.toggle("fa-thumbs-down");
        }
    </script>

</body>

Views/Paper/AddPaper.cshtml
@model IAproject.Models.Paper



@{
    ViewBag.Title = "AddPaper";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddPaper</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>@ViewBag.state</h4>
   
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>

    </div>
</div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Paper/Home.cshtml
@model IEnumerable<IAproject.Models.Paper>

@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Home</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.authers)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>

    <tr>
        @if (item.authers != null)
        {
            @item.authers.ToString();
        }

    </tr>}
</table>

Views/Paper/ShowOnePaper.cshtml
@model IEnumerable<IAproject.ViewModel.PaperAuthors>

@{
    ViewBag.Title = "show";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>show</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.auther)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.paper)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.auther)
            <ul>
                @foreach (var book in item.auther)
                {
                    <li>
                        @book.FirstName
                    </li>
                }
            </ul>


        </td>
        <td>
            @Html.DisplayFor(modelItem => item.paper)
        </td>
       
    </tr>
    }

</table>

Views/Paper/addComment.cshtml
@model IAproject.Models.Comments
@{
    ViewBag.Title = "addComment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<h2>addComment</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Comments</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.paperID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paperID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paperID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AutherID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AutherID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AutherID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<p>Click on the icon to toggle between thumbs-up and thumbs-down (like/dislike):</p>

<i class="fa fa-thumbs-up"></i>

<script>
        function myFunction(x) {
            x.classList.toggle("fa-thumbs-down");
        }
</script>

Views/Paper/show.cshtml
@model IEnumerable<IAproject.ViewModel.PaperAuthors>
@{
    ViewBag.Title = "show";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>show</h1>
<button class="button">
    @Html.ActionLink("Create New", "AddPaper")
    </button>
    <table style="color:gray">


        @foreach (var item in Model)
        {

            <div class="card ">
                <ul>

                    <h2 style=" color:darkseagreen">
                        @Html.DisplayNameFor(model => model.auther)
                    </h2>
                    <h4>
                        @foreach (var Auther in item.auther)
                        {

                            @Html.ActionLink(@Auther.FirstName, "ShowAutherProfile", "Auther", new { id = Auther.Id }, null)
                            <br />


                        }
                    </h4>
                </ul>


                <ul>
                    <h2 style="color:darkseagreen">
                        @Html.DisplayNameFor(model => model.paper)
                    </h2>
                    <h3>Title</h3>
                    @Html.ActionLink(item.paper.Title, "ShowOnePaper", new { id = Guid.Parse(item.paper.id.ToString()) }, null) |

                    <h3>Content</h3>
                    @Html.DisplayFor(modelItem => item.paper.Content)
                </ul>
                <h2>---------------------------------------------</h2>
                <ul>
                    @Html.ActionLink("Like", "AddLike", new { id = Guid.Parse(item.paper.id.ToString()) }, null) |
                    @Html.ActionLink("AddDisLike", "AddDisLike", new { id = Guid.Parse(item.paper.id.ToString()) }, null)

                    @using (Html.BeginForm("addComment", "Paper", new { Id = Guid.Parse(item.paper.id.ToString()) }))
                    {

                        @Html.TextBox("Comment", "")
                       
                        <br />
                        <input type="submit" value="Submit TextBox" />

                    }





                </ul>

            </div>




        }
    </table>





    <html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
]        <style>
            .card {
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                transition: 0.3s;
                width: 40%;
                background-color:antiquewhite;
            }

                .card:hover {
                    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
                }

            .container {
                padding: 3px 20px;
            }
            .button {
                background-color:bisque;
                border: none;
                color: white;
                padding: 15px 32px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                cursor: pointer;
            }
            } 
            
        </style>
    </head>

</html>